apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-k8-multi-com
spec:
  issuerRef: 
    name: letsencrypt-ca-issuer
    kind: ClusterIssuer
  secretName: dev-k8-multi-com
  duration: 2160h
  renewBefore: 360h
  commonName: dev.k8-multi.com
  dnsNames:
    - dev.k8-multi.com
    - www.dev.k8-multi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dev.k8-multi.com
          - www.dev.k8-multi.com