apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce #How many ans how the nodes in K8s can access the storage.
    #ReadWriteOnce: Can be used by a single node
    #ReadOnlyMany: Multiple nodes can read from this storage.
    #ReadWriteMany: Can be read and written to by many nodes.
  resources:
    requests:
      storage: 2Gi #Amount of Storage. Static or Dynamic. 