apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomize-
resources:
  - client-cluster-ip-service.yaml
  - client-deployment.yaml
  - database-persistent-volume-claim.yaml
  - ingress-service.yaml
  - postgres-cluster-ip-service.yaml
  - postgres-deployment.yaml
  - redis-cluster-ip-service.yaml
  - redis-deployment.yaml
  - server-cluster-ip-service.yaml
  - server-deployment.yaml
  - worker-deployment.yaml