apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec: 
      containers:
      - name: server
        image: sonergezgen/multi-server:($TAG)
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-cluster-ip-service #ClustIP service that we've created. We telling that this pods should talk to redis,via it's name.
        - name: REDIS_PORT
          value: "6379"
        - name: PGUSER
          value: postgres
        - name: PGHOST
          value: postgres-cluster-ip-service
        - name: PGDATABASE
          value: postgres
        - name: PGPASSWORD  #The Env variable that our app is expecting to see. 
          valueFrom: 
            secretKeyRef:
              name: pgpassword #The secret name (it can be anything)
              key:  PGPASSWORD #The Key Name that we've put when creating the secret using "kubectl create secret.." (it can be anything)
        - name: PGPORT
          value: "5432"
