apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-client-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.clientDeployment.replicas }}
  selector:
    matchLabels:
      component: web
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: web
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.clientDeployment.client.image.repository }}:{{ .Values.clientDeployment.client.image.tag
          | default .Chart.AppVersion }}
        name: client
        ports:
        - containerPort: 3000
        resources: {}