apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-database-persistent-volume-claim
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.databasePersistentVolumeClaim.storageRequest | quote
        }}
  storageClassName: {{ .Values.pvc.databasePersistentVolumeClaim.storageClass | quote
    }}