apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: dev.k8-multi.com
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-client-cluster-ip-service'
            port:
              number: 3000
        path: /?(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-server-cluster-ip-service'
            port:
              number: 5000
        path: /api/?(.*)
        pathType: Prefix