apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-server-deployment
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.serverDeployment.replicas }}
  selector:
    matchLabels:
      component: server
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: server
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: {{ quote .Values.serverDeployment.server.env.redisHost }}
        - name: REDIS_PORT
          value: {{ quote .Values.serverDeployment.server.env.redisPort }}
        - name: PGUSER
          value: {{ quote .Values.serverDeployment.server.env.pguser }}
        - name: PGHOST
          value: {{ quote .Values.serverDeployment.server.env.pghost }}
        - name: PGDATABASE
          value: {{ quote .Values.serverDeployment.server.env.pgdatabase }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: PGPASSWORD
              name: pgpassword
        - name: PGPORT
          value: {{ quote .Values.serverDeployment.server.env.pgport }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.serverDeployment.server.image.repository }}:{{ .Values.serverDeployment.server.image.tag
          | default .Chart.AppVersion }}
        name: server
        ports:
        - containerPort: 5000
        resources: {}