version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  BeforeInstallAndRunTests:
    machine: #Runner Type, it can be docker, machine ...
      image: ubuntu-2004:202010-01
      docker_layer_caching: true #Gives the docker environment too (It caches the image layers).
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "install & authenticate google cloud sdk"
          command: |
            sudo apt-get update & sudo apt-get install -y curl
            export CLOUD_SDK_REPO="cloud-sdk-(lsb_release -c -s)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list"
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk
            sudo gcloud --quiet components update 
            sudo gcloud --quiet components update kubectl
            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud config set compute/zone ${GCLOUD_COMPUTE_ZONE}
            gcloud container clusters get-credentials ${GCLOUD_CLUSTER_NAME} 
            gcloud projects list --sort-by=projectId --limit=5
      - run:
          name: Docker Login
          command: | 
            echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  before_install_job:
    jobs:
      - BeforeInstallAndRunTests
