apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
replicas:
  - name: client-deployment
    count: 3
  - name: worker-deployment
    count: 1
  - name: server-deployment
    count: 3
images:
  - name: sonergezgen/multi-client
    newTag: latest
  - name: sonergezgen/multi-worker
    newTag: latest
  - name: sonergezgen/multi-server
    newTag: latest
resources:
  - ../../../k8_files
