apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:admin
  policy.csv: |
    p, role:argocd, applications, *, */*, allow
    p, role:argocd, clusters, get, *, allow
    p, role:argocd, repositories, get, *, allow
    p, role:argocd, repositories, create, *, allow
    p, role:argocd, repositories, update, *, allow
    p, role:argocd, repositories, delete, *, allow
    p, role:argocd, logs, get, *, allow
    p, role:argocd, exec, create, */*, allow

    g, username/group/role, role:argocd